# Generated by Django 5.0.7 on 2025-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionmarket',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
